spring:
  application:
    name: irctc-ticket-booking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false # Set to true later to profile your queries

management:
  endpoints:
    metics:
      enabled: true
    web:
      exposure:
        include: health,info,metrics
